### ISSUE TITLE
Разбор статьи IceCube

### ISSUE THREAD

**Issue by bbchkee** [gvd-irkutsk/main#3]
Настя

**Comment by AnastasiiaSemeniuk** [comment]
Заметки по статье. 
- DeepCore плотность в 5 раз превышает плотность остального детектора  -
- Информация о событии представляется в виде серии импульсов за 1 оптический модуль, где каждый импульс содержит в себе время и заряд 
- Порог - few GeVs
- В статье описаны два метода извлечения (выбора) информации для восстановления событий:
    1. Выбор событий с преобладающим не рассеянным светом, который результирует в относительно маленький, но легко восстанавливаемый и надежный набор ивентов 
    2. Чтобы проводить анализ большего объема разных данных был разработан многофункциональный реконструирующий алгоритм, который можно применять к любым ивентам, также он дает более полную информацию о событии, но засчет увеличения вычислительных затрат 
- Для многих анализов, а также для восстановления события используются такие величины как deposited ? energy of event, а также место взаимодействия частицы со льдом

1.2 Event Signatures 

Детектируемые ивенты делятся на две группы:  

- Каскады - любые ливни частиц считаются каскадами,  These include hadronic
showers caused by deep inelastic scattering(глубокое неупругое рассеяния), and electromagnetic showers induced by the electron from νCC interactions. Relativistic, charged particles (β > 1/n) in such showers emit Cherenkov radiation that can be detectedby IceCube DOMs, and for energies between 1–100 GeV,such showers extend approximately 4–6 m in length [19].

- ивенты с треками
In contrast to hadrons and electrons, muons have the potential to travel a sizable distance in the ice while radiating Cherenkov light, leading to a track signature in the detector. In general νCC interactions will produce μ muons, and about 17% of tau leptons produced in νCC in- τeractions decay to muons, while other interactions result only in cascades [20].

Интересует выбор ивентов, которые содержат треки, для определения нейтринного флейвора. 

1.3 Raw Data / Pulses

Данные, приходящие на ФЭУ оцифровываются в форме выделения единичых фотоэлектронов и сохраняются как серия pulses из зарядов и времени. A clustering approach requires all pulses to be causally connected within a distance of at most 150 m and a time difference of at most 1 μs to at least one other pulse in the cluster. The resulting series of pulses per event serve as the input data to the reconstruction algorithms described next in this article. For a typical oscillation event sample, as used in Sec. 4, and after the cleaning described above is applied, the average events contain a total of 17 pulses, distributed over 14 DOMs and 6 strings.

2 santa — Avoiding Scattered Light

The Single-string Antares-inspired Analysis (santa)[23] is an algorithm for the reconstruction of track directions. 

### 2.1 Hit selection

Первый шаг реконструкции - выбор минимально рассеянных фотонов. 

Серии pulses, записанные каждым оптическим модулем комбинируются в hit со временем первого pulse и полным зарядом всех pulses в серии. Чтобы убрать рассеянный свет, мы используем тот факт, что самый большой delay между хитами, которые были произведены нерассеянным светом на двух разных ФЭУ i и j - это время, которое нужно для того, чтобы свет распространялся for a directly
up- or down-going light front to travel from one DOM
to the other, τij = |∆zij |/cice , where |∆zij | is the dis-
tance between DOMs i and j and cice is the speed of
light in ice. Если же время задержки между двумя хитами больше этого максимального времени, то мы понимаем, что часть света все же рассеялась. 

В качестве стартовой точки выбора хитов, выбирается хит i=0  с максимальным зарядом на всем стринге и сначала убираем более ранний хит j, где  $\Delta t_{0j} > \tau_{0j}$  . С этого момента алгоритм повторяется. If fewer than 3
hits remain on a string, the entire string is removed from
the event. If less than 5 hits remain in the event, it can-
not be reconstructed.

2.2 Single-String vs. Multi-String

После процедуры очищения хитов ивенты разделяются на две категории - мультистринговые и одностринговые. 

The second category is single-string events that contain only one string in which modules have observed charges. Since all mod- ules on a single string share approximately the same x and y coordinates, the azimuth angle of a track cannot be reconstructed. (Только зенитный)

2.3 Геометрия Треков в IceCube 

 Чтобы произвести фитирование по методу Хи квадрата на наблюдаемых хитах для постоения гипотетического трека частицы, сначала необходимо опеределить предположительно время прибытия фотона в оптических модуль, который имеет позицию r=(x, y,z). 

Трек характеризуется нормализованным вектороном направления, якорной точкой q и временем t0, в которое точка проходит черех точку q. В этой упрощенной модели подразумевается, что треки бесконечны в обоих направлениях. 

Без рассеяния, все Черенковские фотоны расположены в конусе с открывающим углом $\theta$, вершина которого находится в позиции частицы p(t). Угол вычисляется как косинус(тета)=1/фазовый показатель отражения. 

Формула (2) - получаем так называемое геометрическое время. 

2.4 Процедура фиттирования 

Фитирование проводится для набора параметров $\overrightarrow{\theta} = (\overrightarrow u, \overrightarrow q, t_{0})$,  минимизируется функция хи квдарат (4).
